---
title: "Figures for the MOOC Pivot paper"
author: "José A. Ruipérez Valiente"
date: "12/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This code uses the CSV files tabular data from the *MOOC_Pivot.ipynb* and creates the **raw** figures that were used for the paper. Note out that figures were edited for final publication.

# Imports

```{r imports, message=FALSE, warning=FALSE}
library(pander)
library(ggplot2)
library(tidyverse)
library(reshape2)
library(ggrepel)
library(gridExtra)
library(grid)
require(scales)
```

# Churn rate

```{r figure1}

churn_rate_data <- read.csv2("Table_S1.csv", sep = ",", dec = ".")

churn_rate_data$registration_year = as.factor(churn_rate_data$registration_year)
churn_rate_data$year = factor(churn_rate_data$year,
                                        labels=c("2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18"))

ggplot(data = churn_rate_data) + 
  geom_line(aes(group = registration_year, x = year, y=unique_learners, color=registration_year)) + geom_point(aes(group = registration_year, x = year, y=unique_learners, color=registration_year)) +
  geom_text_repel(aes(label=paste(unique_learners, ' (', round(percentage_retention),'%)', sep = ''), x=year, y=unique_learners), hjust=0, vjust=-1) +
  scale_color_brewer(palette="Set2", labels=c("2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18"), name = "Registration year") + 
  theme_minimal() + theme(legend.position="bottom", plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_continuous(labels = comma) +
  labs(x = 'semester_year', y = 'Unique learners', color = 'Registration year') 
```

# Enrolments and Certifications by HDI Category and Year

```{r figure2}
yearly_hdi_category_data <- read.csv2("Table_S2.csv", sep = ",", dec = ".")

yearly_hdi_category_data$human_development_category = factor(yearly_hdi_category_data$human_development_category, 
                                                             levels = c("very_high_human_development", "high_human_development", "medium_human_development", "low_human_development"))

p_enrolments_hdi <- ggplot(data = yearly_hdi_category_data) + 
  geom_line(aes(y=n_enrolments, x=year, color=human_development_category, group = human_development_category)) + geom_point(aes(y=n_enrolments, x=year, color=human_development_category, group = human_development_category)) +
  geom_text_repel(aes(label=paste(round(p_enrolments_within_year),'%', sep = ''), x=year, y=n_enrolments), hjust=0, vjust=-1) + theme_minimal() + 
  theme(legend.position="right", plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_color_manual(breaks = c("very_high_human_development", "high_human_development", "medium_human_development", "low_human_development"), 
                     values = c("#2b83ba", "#abdda4", "#fdae61", "#d7191c"),
                     labels = c("Very high", "High", "Medium", "Low")) +
  labs(x = '', y = '', fill='region', color = 'HDI human development category', title='Number of enrolments')

p_certifications_hdi <- ggplot(data = yearly_hdi_category_data) + 
  geom_line(aes(y=n_certified, x=year, color=human_development_category, group = human_development_category)) + geom_point(aes(y=n_certified, x=year, color=human_development_category, group = human_development_category)) +
  geom_text_repel(aes(label=paste(round(p_certified_within_year),'%', sep = ''), x=year, y=n_certified), hjust=0, vjust=-1) + theme_minimal() + 
  theme(legend.position="right", plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_color_manual(breaks = c("very_high_human_development", "high_human_development", "medium_human_development", "low_human_development"), 
                     values = c("#2b83ba", "#abdda4", "#fdae61", "#d7191c"),
                     labels = c("Very high", "High", "Medium", "Low")) +
  labs(x = '', y = '', fill='region', color = 'HDI human development category', title='Number of certifications')

grid.arrange(p_enrolments_hdi, p_certifications_hdi, ncol = 1)
```

#  Completion by Cohort 

```{r figure3}
completion_by_cohort <- read.csv2(file = "Table_S3.csv", sep = ",", dec = ".")
completion_by_cohort <- completion_by_cohort[!completion_by_cohort$year == 2018,]
completion_by_cohort <- completion_by_cohort[!completion_by_cohort$year == 2012,]

completion_by_cohort$cohort <- factor(completion_by_cohort$cohort, levels = c("participants", "intend_complete", "verified"))

ggplot(data = completion_by_cohort) + 
  geom_bar(aes(y=p_completed, x=year, fill = cohort), position = "dodge", stat = "identity") + scale_fill_brewer(palette="Set2") + theme_minimal() +
  theme(legend.position="bottom", plot.title = element_text(hjust = 0.5)) + 
  scale_y_continuous(breaks = round(seq(0, 75, by = 5), 1)) +
  labs(x = '', y = 'Percentage completed', fill='cohort', color = 'cohort') 
```